### ISSUE TITLE
Setup on a Raspberry PI x64

### ISSUE THREAD

**Issue by BMWfan** [ich777/docker-enpass#1]
Hey,

i'm trying actually to get the setup running by clonig the repo, creating a docker-compose.yml in the same folder with the following content:
```
version: "3"
services:
  enpass:
    build: ./docker/.
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
     # - /etc/enpass/sync_default.walletx:/root/Documents/Enpass/walletx.db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: "enpass"
```

The container starts for about 15 seconds and reboots, and this endlessly. 

In the logs i see only that entries:
```
---Starting Enpass---
---Ensuring UID: 99 matches user---
usermod: no changes
---Ensuring GID: 100 matches user---
usermod: no changes
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Checking configuration for noVNC---
Nothing to do, noVNC resizing set to default
Nothing to do, noVNC qaulity set to default
Nothing to do, noVNC compression set to default
---Taking ownership of data...---
---Starting...---
---Version Check---
---Enpass v6.8.5.1173 up-to-date---
---Preparing Server---
---Resolution check---
---Checking for old logfiles---
---Checking for old display lock files---
---Starting TurboVNC server---
---Starting Fluxbox---
---Starting noVNC server---
WebSocket server settings:
  - Listen on :8080
  - Web server. Web root: /usr/share/novnc
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
```
How can i get out more informations to know where the issue lies that it reboots everytime?

Greetings

Daniel
